# Generated by Django 2.2.7 on 2019-11-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='not_selected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_selected', to='compare.Person'),
        ),
    ]
