# Generated by Django 2.2.7 on 2019-12-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20191106_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Person')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Expert')),
            ],
        ),
    ]
