# Generated by Django 2.2.7 on 2019-12-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='choice',
            new_name='person',
        ),
    ]
