# Generated by Django 2.2.7 on 2019-12-01 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_auto_20191201_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='compare.Person'),
        ),
    ]
