# Generated by Django 2.2.7 on 2019-12-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_auto_20191201_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compare',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compare.Expert'),
        ),
    ]
